# This workflow will automatically build and deploy the documentation to GitHub Pages.
# Mildly out of date tutorial: https://sorokin.engineer/posts/en/github-pages-lazydocs-mkdocs.html

name: docs

on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11 (lazydocs fails with greater versions)
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.6.1
      - name: View poetry --help
        run: poetry --help
      - name: Install dependencies
        run: |
          poetry install
      - name: View lazydocs --help
        run: poetry run lazydocs --help
      - name: Build and deploy documentation
        run: |
          poetry run lazydocs --output-path docs/api \
                  --overview-file="README.md" \
                  --src-base-url="https://github.com/michelcrypt4d4mus/$YARALYZER_PKG/blob/main/" \
                  --ignored-modules="yaralyzer.util.helpers" \
                  "$YARALYZER_PKG" \
                  "$YARALYZER_PKG/decoding" \
                  "$YARALYZER_PKG/encoding_detection" \
                  "$YARALYZER_PKG/output" \
                  "$YARALYZER_PKG/util" \
                  "$YARALYZER_PKG/yara"
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force


# source ./scripts/build_docs.sh
